services:
  app:
    image: apple860601/flasky
    command: "flask run -h '0.0.0.0'"
    ports:
      - 6001:5000
    working_dir: /SHOPCRUB/flask_web
    volumes:
      - ./:/SHOPCRUB
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: apple80558
      MYSQL_DB: flaskdb
      FLASK_APP: flasky.py
      FLASK_DEBUG: True
      FLASKY_ADMIN: apple860601@gmail.com
      ADMIN_NAME: shiocho
      ADMIN_PASSWORD: apple80558
      ADMIN_LOCATION: 台北市中正區重慶南路一段122號
      # FLASK_ENV: development

  mysql:
    image: mysql:8.0.19
    volumes:
      - mysqldb:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: apple80558
      MYSQL_DATABASE: flaskdb
    ports:
      - 3306:3306

volumes:
  mysqldb: